language: python
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - make html
before_deploy:
  - aws s3 rm s3://handbook.mattermost.com/ --recursive --region us-east-1
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEYß
    bucket: handbook.mattermost.com
    local_dir: build/html
    acl: public_read
    region: us-east-1
    skip_cleanup: true
    detect_encoding: true
    on:
      repo: mattermost/mattermost-handbook
      branch: master
      python: 3.6
